import "oaidl.idl";
import "ocidl.idl";

[
    object,
    uuid(C0C62619-3BC1-4095-9B9A-84503E37DAA5),
    version(1.0),
    helpstring("IComTest interface")
]
interface IComTest : IUnknown
{
    HRESULT WhoAmI([out] LPWSTR *pwszWhoAmI);
}

[
    object,
    uuid(AEC109A3-62A1-4FAA-BFDC-C433B1C4CF70),
    version(1.0),
    helpstring("IZSS interface")
]
interface IZSS : IUnknown
{
    HRESULT reverseNumber([in] int x, [out, retval] int* result);
}
